Update metadata, version, and changelog for 645 area code
mobi/telephone_number pull request #133
Opened 2024-02-28 14:11 UTC by ankita-ac

2024-02-28 20:46 UTC, jaykravetz approved these changes

2024-03-01 07:09 UTC, ankit-tangoe requested changes

2024-03-01 07:09 UTC, ankit-tangoe commented on .DS_Store
Please remove this file

2024-03-01 07:09 UTC, ankit-tangoe commented on data/.DS_Store
Please remove this file.

2024-03-05 06:01 UTC, ankita-ac commented on data/.DS_Store
Resolved

2024-03-05 06:01 UTC, ankita-ac commented on .DS_Store
Resolved

2024-03-05 06:02 UTC, ankit-tangoe approved these changes
LGTM!

2024-03-07 16:11 UTC, merged